######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 4 15:42:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Const.h GameItem.h GameWidget.h
SOURCES += GameInit.cpp GameItem.cpp GameWidget.cpp RiverAndFrogBonus.cpp
RESOURCES += res.qrc
