######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 29 14:39:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Const.h GameWidget.h
SOURCES += GameWidget.cpp RiverAndFrogBonus.cpp
RESOURCES += res.qrc
